[package]
name = "coauthor"
version = "0.1.0"
authors = ["Johan Tell <johan@mintcore.se>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.92", features = ["derive"]}
shellexpand = "1.0.0"
toml = "0.5"
exitfailure = "0.5.1"
