[package]
name = "coauthor"
version = "0.2.0"
authors = ["Johan Tell <johan@mintcore.se>"]
edition = "2018"

[dependencies]
exitfailure = "0.5.1"
regex = "1"
serde = { version = "1.0.92", features = ["derive"]}
shellexpand = "1.0.0"
toml = "0.5"
reqwest = "0.9.22"
